services:
  - type: web
    name: ikshuvruddhi-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_main:app --host 0.0.0.0 --port 
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CDSE_CLIENT_ID
        sync: false
      - key: CDSE_CLIENT_SECRET
        sync: false
